# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-12 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appuser_created_by', to='app_users.AppUser'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appuser_updated_by', to='app_users.AppUser'),
        ),
    ]
