# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20171012_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='deactivated_on',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='reactivated_by',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='reactivated_on',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='updated_by',
        ),
    ]
