# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topiccomment',
            name='down_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topiccomment',
            name='meh_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topiccomment',
            name='parent_topic_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='st.TopicComment'),
        ),
        migrations.AddField(
            model_name='topiccomment',
            name='up_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topiccomment',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
