# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20180124_0739'),
        ('st', '0002_auto_20180124_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('meh', 'meh')], max_length=10, verbose_name='self')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.AppUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='meh_votes',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='up_votes',
        ),
        migrations.RemoveField(
            model_name='topiccomment',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='topiccomment',
            name='meh_votes',
        ),
        migrations.RemoveField(
            model_name='topiccomment',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st.Topic'),
        ),
    ]
