# Generated by Django 2.0.1 on 2018-01-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0003_auto_20180124_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='updated',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='topiccomment',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='topiccomment',
            old_name='updated',
            new_name='updated_on',
        ),
    ]
