# Generated by Django 2.0.1 on 2018-01-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0005_auto_20180125_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='prev_vote_type',
            field=models.CharField(blank=True, choices=[('up', 'up'), ('down', 'down'), ('meh', 'meh')], max_length=10, null=True, verbose_name='self'),
        ),
    ]
