# Generated by Django 2.0.1 on 2018-01-30 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
        ('meetings', '0002_auto_20180129_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItemStackEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10)),
                ('allotted_duration', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('opened_on', models.DateTimeField(blank=True, null=True)),
                ('closed_on', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='agendaitemstackentry',
            name='agenda_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.AgendaItem'),
        ),
        migrations.AddField(
            model_name='agendaitemstackentry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.AppUser'),
        ),
    ]
