# Generated by Django 2.0.1 on 2018-01-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20180130_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaitemvote',
            name='agenda_item',
        ),
        migrations.RemoveField(
            model_name='agendaitemvote',
            name='vote',
        ),
        migrations.DeleteModel(
            name='AgendaItemVote',
        ),
    ]
