# Generated by Django 2.0.1 on 2018-02-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meetinginvitation_meetingparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginvitation',
            name='accepted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='joined_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
