# Generated by Django 2.0.1 on 2018-02-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20180201_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetinginvitation',
            old_name='rejected_on',
            new_name='declined_on',
        ),
        migrations.AlterField(
            model_name='meetinginvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=10),
        ),
    ]
