# Generated by Django 2.0.1 on 2018-02-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_auto_20180201_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='body',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
