# Generated by Django 2.0.1 on 2018-02-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_auto_20180201_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='topiccomment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='topiccomment',
            name='parent_topic_comment',
        ),
        migrations.RemoveField(
            model_name='topiccomment',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='agendaitemvote',
            name='prev_vote_type',
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='TopicComment',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
